### ISSUE TITLE
Hide your token

### ISSUE THREAD

**Issue by robertmartin8** [yeoteeshenmark/priceactionscore#1]
Hi Mark,

Saw your post on LinkedIn, nicely done!

I noticed that in your screenshot, your API token was visible. Similarly, in this repository, your token is there. This is bad practice because now anyone can use your token to make requests. Even if it's a free account, someone else can use all of your API calls. 

Best,
Robert

**Comment by yeoteeshenmark** [comment]
Hi Robert, thank you for letting me know - very good shout!
